name: build-clients

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.3

    - name: Set path
      run: echo "/protoc/bin:$GOPATH/bin" >> $GITHUB_PATH

    - name: Install system dependencies
      run: |
        apt update && apt install -y unzip gcc-mingw-w64-i686 gcc-mingw-w64-x86-64 gcc-multilib
        wget https://github.com/protocolbuffers/protobuf/releases/download/v22.3/protoc-22.3-linux-x86_64.zip
        sudo unzip protoc-22.3-linux-x86_64.zip -d /protoc
        rm protoc-22.3-linux-x86_64.zip
        go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2

    - name: Build protoc
      run: |
        cd grpc
        ./build_protoc.sh
        cd ..

    - name: Get packages
      run: go get -d -v ./... && go install -v ./...

    - name: Build windows 32 bit exe
      run: |
        ./build_client.sh -host 127.0.0.1 -name dummy -outputfile dummywin32.exe -bintype exe -platform win -arch x86
