name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Set path
      run: echo "/protoc/bin:$GOPATH/bin" >> $GITHUB_PATH

    - name: Install system dependencies
      run: |
        wget https://github.com/protocolbuffers/protobuf/releases/download/v22.3/protoc-22.3-linux-x86_64.zip
        sudo unzip protoc-22.3-linux-x86_64.zip -d /protoc
        rm protoc-22.3-linux-x86_64.zip
        go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2

    - name: Build protoc
      run: |
        cd grpc
        ./build_protoc.sh
        cd ..

    - name: Get packages
      run: go get -d -v ./... && go install -v ./...

    - name: Build gtuncli
      run: |
        mkdir build
        cd gtuncli && go build -o ../build/gtuncli gtuncli.go && cd ..
      
    - name: Publish artifact
      uses: actions/upload-artifact@v2
      with:
        name: gtuncli
        path: build/gtuncli
